ALTER TRIGGER [dbo].[TRIGGER_LENHDAT]
ON [dbo].[LENHDAT] AFTER INSERT, UPDATE
AS
BEGIN
	IF EXISTS (SELECT MACP FROM BANGGIATRUCTUYEN WHERE MACP = (SELECT MACP FROM inserted))
	BEGIN
		DECLARE @CrsrVar CURSOR,
				@MACP CHAR(7),
				@GIADUMUA1 FLOAT, 
				@KLDUMUA1 INT,
				@GIADUMUA2 FLOAT, 
				@KLDUMUA2 INT,
				@GIADUBAN1 FLOAT, 
				@KLDUBAN1 INT,
				@GIADUBAN2 FLOAT, 
				@KLDUBAN2 INT
		SET @CrsrVar = CURSOR FOR SELECT DISTINCT MACP FROM LENHDAT

		OPEN @CrsrVar -- MO CON TRO

		FETCH NEXT FROM @CrsrVar INTO @MACP --DOC DONG DAU TIEN
		WHILE(@@FETCH_STATUS <>-1)
		BEGIN
			
			SET @GIADUMUA1 = (SELECT MAX(GIADAT) 
				FROM LENHDAT WHERE MACP = @MACP AND LOAIGD='M' AND SOLUONG > 0 AND CAST(NGAYDAT AS DATE) = CAST(GETDATE() AS DATE))
				-----------
			SET @KLDUMUA1 = (SELECT SUM(SOLUONG) 
				FROM LENHDAT WHERE MACP = @MACP AND LOAIGD='M' AND SOLUONG > 0 AND CAST(NGAYDAT AS DATE) = CAST(GETDATE() AS DATE) AND GIADAT = @GIADUMUA1)
				--------------
			SET @GIADUMUA2 = (SELECT MAX(GIADAT) 
				FROM LENHDAT WHERE MACP = @MACP AND LOAIGD='M' AND SOLUONG > 0 AND CAST(NGAYDAT AS DATE) = CAST(GETDATE() AS DATE) AND GIADAT < @GIADUMUA1)
				----------------------
			SET @KLDUMUA2 = (SELECT SUM(SOLUONG) 
				FROM LENHDAT WHERE MACP = @MACP AND LOAIGD='M' AND SOLUONG > 0 AND CAST(NGAYDAT AS DATE) = CAST(GETDATE() AS DATE) AND GIADAT = @GIADUMUA2 AND GIADAT < @GIADUMUA1)
				----------------------
			SET @GIADUBAN1 = (SELECT MIN(GIADAT) 
				FROM LENHDAT WHERE MACP = @MACP AND LOAIGD='B' AND SOLUONG > 0 AND CAST(NGAYDAT AS DATE) = CAST(GETDATE() AS DATE))
				--------------
			SET @KLDUBAN1 = (SELECT SUM(SOLUONG) 
				FROM LENHDAT WHERE MACP = @MACP AND LOAIGD='B' AND SOLUONG > 0 AND CAST(NGAYDAT AS DATE) = CAST(GETDATE() AS DATE) AND GIADAT = @GIADUBAN1)
				----------------------
			SET @GIADUBAN2 = (SELECT MIN(GIADAT) 
				FROM LENHDAT WHERE MACP = @MACP AND LOAIGD='B' AND SOLUONG > 0 AND CAST(NGAYDAT AS DATE) = CAST(GETDATE() AS DATE) AND GIADAT > @GIADUBAN1)
				--------------------
			SET @KLDUBAN2 = (SELECT SUM(SOLUONG) 
				FROM LENHDAT WHERE MACP = @MACP AND LOAIGD='B' AND SOLUONG > 0 AND CAST(NGAYDAT AS DATE) = CAST(GETDATE() AS DATE) AND GIADAT = @GIADUBAN2 AND GIADAT > @GIADUBAN1)
			
			UPDATE BANGGIATRUCTUYEN SET GIADUMUA1 = @GIADUMUA1,
										KLDUMUA1 = @KLDUMUA1,
										GIADUMUA2 = @GIADUMUA2, 
										KLDUMUA2 = @KLDUMUA2,
										GIADUBAN1 = @GIADUBAN1, 
										KLDUBAN1 = @KLDUBAN1,
										GIADUBAN2 = @GIADUBAN2, 
										KLDUBAN2 = @KLDUBAN2
										WHERE MACP = @MACP 
			FETCH NEXT FROM @CrsrVar INTO @MACP -- DOC DONG TIEP THEO
		END
		CLOSE @CrsrVar 
		DEALLOCATE @CrsrVar
	END
	ELSE
	BEGIN
		DECLARE @MACOPHIEU CHAR(7)
		SET @MACOPHIEU = (SELECT MACP FROM inserted)
		SET @GIADUMUA1 = (SELECT MAX(GIADAT) 
				FROM LENHDAT WHERE MACP = @MACOPHIEU AND LOAIGD='M' AND SOLUONG > 0 AND CAST(NGAYDAT AS DATE) = CAST(GETDATE() AS DATE))
				-----------
		SET @KLDUMUA1 = (SELECT SUM(SOLUONG) 
				FROM LENHDAT WHERE MACP = @MACOPHIEU AND LOAIGD='M' AND SOLUONG > 0 AND CAST(NGAYDAT AS DATE) = CAST(GETDATE() AS DATE) AND GIADAT = @GIADUMUA1)
				--------------
		SET @GIADUBAN1 = (SELECT MIN(GIADAT) 
				FROM LENHDAT WHERE MACP = @MACOPHIEU AND LOAIGD='B' AND SOLUONG > 0 AND CAST(NGAYDAT AS DATE) = CAST(GETDATE() AS DATE))
				--------------
		SET @KLDUBAN1 = (SELECT SUM(SOLUONG) 
				FROM LENHDAT WHERE MACP = @MACOPHIEU AND LOAIGD='B' AND SOLUONG > 0 AND CAST(NGAYDAT AS DATE) = CAST(GETDATE() AS DATE) AND GIADAT = @GIADUBAN1)
				----------------------
		INSERT INTO BANGGIATRUCTUYEN(MACP, GIADUMUA1, KLDUMUA1, GIADUBAN1, KLDUBAN1)
			VALUES(@MACOPHIEU, @GIADUMUA1, @KLDUMUA1, @GIADUBAN1, @KLDUBAN1)
	END
END