ALTER TRIGGER  [dbo].[TR_After_LENHDAT] 
   ON  [dbo].[LENHDAT] 
   AFTER INSERT, UPDATE, DELETE 
AS 
BEGIN
	DECLARE 
		@CrsrVar CURSOR,
		@MACP char(7),
		@GIADUMUA1 FLOAT, 
		@KLDUMUA1 INT,
		@GIADUMUA2 FLOAT, 
		@KLDUMUA2 INT,
		@GIADUBAN1 FLOAT, 
		@KLDUBAN1 INT,
		@GIADUBAN2 FLOAT, 
		@KLDUBAN2 INT,
		@COUNT INT

	SET @CrsrVar = CURSOR FOR (SELECT DISTINCT MACP FROM LENHDAT) --DU LIEU TRO TOI
	
	OPEN @CrsrVar --MO CON TRO
	FETCH NEXT FROM @CrsrVar INTO @MACP --DOC DONG DAU TIEN

	SELECT @COUNT = COUNT(*) FROM BANGGIATRUCTUYEN
	IF @COUNT > 0 --NEU > 0 THÌ UPDATE
	BEGIN
		WHILE(@@FETCH_STATUS <>-1)
		BEGIN
			SET	@GIADUMUA1 = 0
			SET	@KLDUMUA1 = 0
			SET	@GIADUMUA2 = 0 
			SET	@KLDUMUA2 = 0 
			SET	@GIADUBAN1 = 0 
			SET	@KLDUBAN1 = 0 
			SET	@GIADUBAN2 = 0 
			SET	@KLDUBAN2 = 0

			IF EXISTS (SELECT MACP FROM BANGGIATRUCTUYEN WHERE MACP = (SELECT MACP FROM inserted))
			BEGIN
				
			END
			ELSE
			BEGIN

			END

			--LAY GIADUMUA THAP NHAT
			SELECT @GIADUMUA1 = GIADAT FROM (
			   SELECT TOP (2)  ROW_NUMBER() OVER(ORDER BY GIADAT ASC) AS RowNumber, * FROM LENHDAT --TU THAP DEN CAO
				WHERE MACP = @MACP AND LOAIGD='M' AND SOLUONG > 0 AND CAST(NGAYDAT AS DATE) = CAST(GETDATE() AS DATE )) ROW
					WHERE RowNumber = 1
			--NEU GIADUMUA <> 0 THI TINH TONG KLDUMUA
			IF(@GIADUMUA1 <> 0)
			BEGIN
				SELECT @KLDUMUA1 = SUM(LD.SOLUONG) FROM 
					(SELECT * FROM LENHDAT
						WHERE MACP = @MACP AND LOAIGD='M' AND SOLUONG > 0 AND CAST(NGAYDAT AS DATE) = CAST(GETDATE() AS DATE) AND GIADAT = @GIADUMUA1) LD
			END

			--CAP NHAT GIADUMUA1 VA KLDUMUA1
			UPDATE BANGGIATRUCTUYEN
	 			SET GIADUMUA1= @GIADUMUA1, 
					KLDUMUA1 = @KLDUMUA1
			WHERE MACP = @MACP 

			--LAY GIADUMUA THAP THU 2
			SELECT @GIADUMUA2 = GIADAT FROM (
			   SELECT TOP (2)  ROW_NUMBER() OVER(ORDER BY GIADAT ASC) AS RowNumber, * FROM LENHDAT 
				WHERE MACP = @MACP AND LOAIGD='M' AND SOLUONG > 0 AND CAST(NGAYDAT AS DATE) = CAST(GETDATE() AS DATE )) ROW
					WHERE RowNumber = 2

			IF(@GIADUMUA2 <> 0)
			BEGIN
				SELECT @KLDUMUA2 = SUM(LD.SOLUONG) FROM 
					(SELECT * FROM LENHDAT
						WHERE MACP = @MACP AND LOAIGD='M' AND SOLUONG > 0 AND CAST(NGAYDAT AS DATE) = CAST(GETDATE() AS DATE) AND GIADAT = @GIADUMUA2) LD
			END

			UPDATE BANGGIATRUCTUYEN
	 			SET GIADUMUA2= @GIADUMUA2, 
					KLDUMUA2 = @KLDUMUA2
			WHERE MACP = @MACP 

			--LAY GIADUBAN CAO NHAT
			SELECT @GIADUBAN1 = GIADAT FROM (
			   SELECT TOP (2)  ROW_NUMBER() OVER(ORDER BY GIADAT DESC) AS RowNumber, * FROM LENHDAT --CAO XUONG THAP
				WHERE MACP = @MACP AND LOAIGD='B' AND SOLUONG > 0 AND CAST(NGAYDAT AS DATE) = CAST(GETDATE() AS DATE )) ROW
					WHERE RowNumber = 1

			IF(@GIADUBAN1 <> 0)
			BEGIN
				SELECT @KLDUBAN1 = SUM(LD.SOLUONG) FROM 
				(SELECT * FROM LENHDAT
					WHERE MACP = @MACP AND LOAIGD='B' AND SOLUONG > 0 AND CAST(NGAYDAT AS DATE) = CAST(GETDATE() AS DATE) AND GIADAT = @GIADUBAN1) LD
			END

			UPDATE BANGGIATRUCTUYEN
	 			SET GIADUBAN1= @GIADUBAN1, 
					KLDUBAN1 = @KLDUBAN1
			WHERE MACP = @MACP 

			--LAY GIDUBAN CAO THU 2
			SELECT @GIADUBAN2 = GIADAT FROM (
			   SELECT TOP (2)  ROW_NUMBER() OVER(ORDER BY GIADAT DESC) AS RowNumber, * FROM LENHDAT 
				WHERE MACP = @MACP AND LOAIGD='B' AND SOLUONG > 0 AND CAST(NGAYDAT AS DATE) = CAST(GETDATE() AS DATE )) ROW
					WHERE RowNumber = 2

			IF(@GIADUBAN2 <> 0)
			BEGIN
				SELECT @KLDUBAN2 = SUM(LD.SOLUONG) FROM 
					(SELECT * FROM LENHDAT
						WHERE MACP = @MACP AND LOAIGD='B' AND SOLUONG > 0 AND CAST(NGAYDAT AS DATE) = CAST(GETDATE() AS DATE) AND GIADAT = @GIADUBAN2) LD
			END

			UPDATE BANGGIATRUCTUYEN
	 			SET GIADUBAN2= @GIADUBAN2, 
					KLDUBAN2 = @KLDUBAN2
			WHERE MACP = @MACP
			FETCH NEXT FROM @CrsrVar INTO @MACP -- DOC DONG TIEP THEO
		END
	END
	ELSE --NGUOC LAI THI INSERT 
	BEGIN
		WHILE(@@FETCH_STATUS <>-1)
		BEGIN
			SET	@GIADUMUA1 = 0
			SET	@KLDUMUA1 = 0
			SET	@GIADUMUA2 = 0 
			SET	@KLDUMUA2 = 0 
			SET	@GIADUBAN1 = 0 
			SET	@KLDUBAN1 = 0 
			SET	@GIADUBAN2 = 0 
			SET	@KLDUBAN2 = 0

			--LAY GIADUMUA THAP NHAT
			SELECT @GIADUMUA1 = GIADAT FROM (
			   SELECT TOP (2)  ROW_NUMBER() OVER(ORDER BY GIADAT ASC) AS RowNumber, * FROM LENHDAT --TU THAP DEN CAO
				WHERE MACP = @MACP AND LOAIGD='M' AND SOLUONG > 0 AND CAST(NGAYDAT AS DATE) = CAST(GETDATE() AS DATE )) ROW
					WHERE RowNumber = 1
			--NEU GIADUMUA <> 0 THI TINH TONG KLDUMUA
			IF(@GIADUMUA1 <> 0)
			BEGIN
				SELECT @KLDUMUA1 = SUM(LD.SOLUONG) FROM 
					(SELECT * FROM LENHDAT
						WHERE MACP = @MACP AND LOAIGD='M' AND SOLUONG > 0 AND CAST(NGAYDAT AS DATE) = CAST(GETDATE() AS DATE) AND GIADAT = @GIADUMUA1) LD
			END

			
			--LAY GIADUMUA THAP THU 2
			SELECT @GIADUMUA2 = GIADAT FROM (
			   SELECT TOP (2)  ROW_NUMBER() OVER(ORDER BY GIADAT ASC) AS RowNumber, * FROM LENHDAT 
				WHERE MACP = @MACP AND LOAIGD='M' AND SOLUONG > 0 AND CAST(NGAYDAT AS DATE) = CAST(GETDATE() AS DATE )) ROW
					WHERE RowNumber = 2

			IF(@GIADUMUA2 <> 0)
			BEGIN
				SELECT @KLDUMUA2 = SUM(LD.SOLUONG) FROM 
					(SELECT * FROM LENHDAT
						WHERE MACP = @MACP AND LOAIGD='M' AND SOLUONG > 0 AND CAST(NGAYDAT AS DATE) = CAST(GETDATE() AS DATE) AND GIADAT = @GIADUMUA2) LD
			END

			--LAY GIADUBAN CAO NHAT
			SELECT @GIADUBAN1 = GIADAT FROM (
			   SELECT TOP (2)  ROW_NUMBER() OVER(ORDER BY GIADAT DESC) AS RowNumber, * FROM LENHDAT --CAO XUONG THAP
				WHERE MACP = @MACP AND LOAIGD='B' AND SOLUONG > 0 AND CAST(NGAYDAT AS DATE) = CAST(GETDATE() AS DATE )) ROW
					WHERE RowNumber = 1

			IF(@GIADUBAN1 <> 0)
			BEGIN
				SELECT @KLDUBAN1 = SUM(LD.SOLUONG) FROM 
				(SELECT * FROM LENHDAT
					WHERE MACP = @MACP AND LOAIGD='B' AND SOLUONG > 0 AND CAST(NGAYDAT AS DATE) = CAST(GETDATE() AS DATE) AND GIADAT = @GIADUBAN1) LD
			END

			--LAY GIDUBAN CAO THU 2
			SELECT @GIADUBAN2 = GIADAT FROM (
			   SELECT TOP (2)  ROW_NUMBER() OVER(ORDER BY GIADAT DESC) AS RowNumber, * FROM LENHDAT 
				WHERE MACP = @MACP AND LOAIGD='B' AND SOLUONG > 0 AND CAST(NGAYDAT AS DATE) = CAST(GETDATE() AS DATE )) ROW
					WHERE RowNumber = 2

			IF(@GIADUBAN2 <> 0)
			BEGIN
				SELECT @KLDUBAN2 = SUM(LD.SOLUONG) FROM 
					(SELECT * FROM LENHDAT
						WHERE MACP = @MACP AND LOAIGD='B' AND SOLUONG > 0 AND CAST(NGAYDAT AS DATE) = CAST(GETDATE() AS DATE) AND GIADAT = @GIADUBAN2) LD
			END

			INSERT INTO BANGGIATRUCTUYEN (MACP, GIADUMUA1, KLDUMUA1, GIADUMUA2, KLDUMUA2, GIAKHOP, KLKHOP, GIADUBAN1, KLDUBAN1, GIADUBAN2, KLDUBAN2) VALUES (@MACP, @GIADUMUA1, @KLDUMUA1, @GIADUMUA2, @KLDUMUA2, 0, 0, @GIADUBAN1, @KLDUBAN1, @GIADUBAN2, @KLDUBAN2)
			FETCH NEXT FROM @CrsrVar INTO @MACP -- DOC DONG TIEP THEO
		END
	END
END
CLOSE @CrsrVar --DONG CURSOR
DEALLOCATE @CrsrVar --GIAI PHONG TAI NGUYEN