ALTER TRIGGER  [dbo].[TR_After_LENHKHOP] 
   ON  [dbo].LENHKHOP 
   AFTER INSERT, UPDATE, DELETE 
AS 
BEGIN
	DECLARE 
		@CrsrVar CURSOR,
		@MACP char(7),
		@GIAKHOP FLOAT, 
		@KLKHOP INT
	SET @CrsrVar = CURSOR KEYSET FOR (SELECT DISTINCT MACP FROM LENHDAT)
	OPEN @CrsrVar 
	FETCH NEXT FROM @CrsrVar INTO @MACP
	WHILE(@@FETCH_STATUS <>-1)
	BEGIN
		WITH temp2 AS
		(
		SELECT TOP 1  ROW_NUMBER() OVER(ORDER BY IDKHOP ASC) AS RowNumber, * 
			FROM LENHKHOP LK INNER JOIN LENHDAT LD ON LK.IDLENHDAT = LD.ID
					WHERE LD.MACP = @MACP AND CAST(NGAYKHOP AS DATE) = CAST(GETDATE() AS DATE) 
		) 
		SELECT @GIAKHOP = GIAKHOP, @KLKHOP = SOLUONGKHOP
		FROM temp2
		WHERE RowNumber = 1

		UPDATE BANGGIATRUCTUYEN
	 	SET GIAKHOP = @GIAKHOP,
			KLKHOP = @KLKHOP
		WHERE MACP = @MACP
		FETCH NEXT FROM @CrsrVar INTO @MACP
	END
END
CLOSE @CrsrVar 
DEALLOCATE @CrsrVar